### ISSUE TITLE
Cache support

### ISSUE THREAD

**Issue by sobolevn** [life4/flakehell#23]
It would be awesome to have cache support for linting.
What do I mean? `flake8` by default checks all files, even if they are unchanged since the last run. It slows down the whole process and bring no additional value: files will have the same result.

What do I suggest? I suggest to cache the intermediate results and collect new files based on that. If the file is changed: then we recheck it. No? Otherwise, we show the cached result.

It should not be enabled by default I guess.

**Comment by orsinium** [comment]
Awesome!

**Comment by orsinium** [comment]
Cache hash includes:

1. Full file path
1. Settings
1. Installed plugins

Let's for the beginning add in cache only files without any warnings happened. In most cases, warnings can happen only in changed files, and from that assumption, we can keep the cache much simpler and smaller.

**Comment by orsinium** [comment]
I think, that's a too complex task for hacktoberfest.

**Comment by sobolevn** [comment]
❤️
