### ISSUE TITLE
Support setup.cfg

### ISSUE THREAD

**Issue by sobolevn** [life4/flakehell#3]
Currently we have a conflict: 
- `flake8` supports `.flake8`, `setup.cfg`, and `tox.ini`
- `flakehell` supports `pyproject.toml`

In case you want to use both tools - you need to have two copies of the config.
I suggest to support both `pyproject.toml` and `setup.cfg` (in this order).

The same also applies to `base = ` property.

**Comment by orsinium** [comment]
Have you checked it? All Flake8 configs should be read before toml

**Comment by sobolevn** [comment]
Yes, `flake8` configs work. But, you cannot configure `flakehell` in the same file. That's strange.

**Comment by orsinium** [comment]
Yes, flakehell is a modern tool with config only in pyproject.toml. Flake8 configs supported for backward compatibility. FlakeHell's own config only in one format and in one place by design.

Let's keep this issue to not forget to document configs priority.
