### ISSUE TITLE
Mention verbosity CLI args in the help hints

### ISSUE THREAD

**Issue by webknjaz** [life4/flakehell#36]
So I've _accidentally_ discovered that there's `-v` and `-vv` which make flakehell print out more details about what's going on.

Running it with `--help` doesn't mention any of it. I think it should since it's useful for debugging and not everyone knows about this convention.

**Comment by orsinium** [comment]
It's a key from flake8, and flakehell shows the original help from flake8 as well. So, we have no power here. I was thinking about improving it but so. However, I'm almost sure it's listed in the help. I'll check it today.

**Comment by webknjaz** [comment]
I checked before posting the issue and it was not there

**Comment by orsinium** [comment]
Wow, we've lost an entire flake8 help.
