### ISSUE TITLE
[docs] Version is 0.0.0

### ISSUE THREAD

**Issue by webknjaz** [life4/flakehell#38]
It shows up in the titles of all pages @ RTD and is hardcoded here: https://github.com/life4/flakehell/blob/e32c611/docs/conf.py#L36-L37.
It shouldn't be hard to import the version from `__init__`.

**Comment by orsinium** [comment]
We're using one-version docs that means the version can't be chosen anywhere or appears in URLs. That it is shown in the title is bad. Let's keep it open, I'm going to add in `dephell project bump` support for sphinx config.

**Comment by webknjaz** [comment]
@orsinium maybe add `version = 'rolling'` or `version = 'master'` in `conf.py` with an appropriate comment then?

**Comment by orsinium** [comment]
Fixed in #58
https://github.com/dephell/dephell/pull/407
Thank you for attention to the details :)
