### ISSUE TITLE
Separate base (common) config from the local config

### ISSUE THREAD

**Issue by sobolevn** [life4/flakehell#4]
Currently when we specify `base =` property we have to extend the whole configuration that is preset in this file.

However, it might contain some local settings: for example rules and settings that are applicable to other projects, but are required for the base one. 

Real-life example: https://github.com/wemake-services/wemake-python-styleguide/blob/master/setup.cfg#L26 This is a mix of local config and base-configuration.

When we create a preset there are must be two phases:
- `flakehell` preset definition
- local configuration that can extend the base preset

All other repos should extend the defined preset and ignore local configuration.
I hope that this makes sense.

**Comment by orsinium** [comment]
You can do it in this way:

1. Specify presets in `flakehell-base.toml`
1. Use `base = "flakehell-base.toml"` in `pyproject.toml` of this project.
1. Use `base = "https://github.com/.../flakehell-base.toml"` in `pyproject.toml` of another project.

**Comment by orsinium** [comment]
Feel free to re-open if the described above workaround doesn't work for you.
