### ISSUE TITLE
Make pylint plugin optional

### ISSUE THREAD

**Issue by auscompgeek** [life4/flakehell#41]
When I install flakehell, it pulls in pylint and the pylint plugin is enabled by default. This is extremely annoying as this means I also get pylint warnings when I run plain flake8.

**Comment by orsinium** [comment]
Well, it can't be optional. Flake8 runs all installed plugins. Possible solutions:

1. Use flakehell. It's **the main** goal of the project: to give you control over installed plugins.
1. Keep flakehell and flake8 in separate environment if you need both (IDK why but so). [DepHell](https://github.com/dephell/dephell) can keep a separate environment for every tool.
1. Exclude pylint codes in flake8 config.
1. Open an issue in flake8 to make it possible to disable plugins.

Anyway, I can't fix bugs in flake8. I mean. yes, I can, and it's exactly what flakehell does.

**Comment by auscompgeek** [comment]
I don't see why the pylint plugin can't be a separate package.
