### ISSUE TITLE
flake8helled vs stdin

### ISSUE THREAD

**Issue by bid0uille** [life4/flakehell#44]
``flake8 --stdin-display-name filename - < file.py`` does allow to feed flake8 via stdin while seeing a given filename (rather than "stdin") in the report
``flake8helled --stdin-display-name filename - < file.py`` doesn't work cause it interprets the "-" as a file in the current directory, given the following error:
``FileNotFoundError: [Errno 2] No such file or directory: '/path/to/current/directory/-'``

I didn't investigate further for now, and I'm afraid that it's beyond my competence. Or is there an obvious solution?
Thanks for attention :)

**Comment by k3rni** [comment]
This bit me when I was trying to substitute `flake8helled` as the linter executable in [ale](https://github.com/dense-analysis/ale)'s flake8 module.

**Comment by orsinium** [comment]
The fix is released. Please, upgrade flakehell to 0.3.5
