### ISSUE TITLE
Refactoring mode

### ISSUE THREAD

**Issue by sobolevn** [life4/flakehell#5]
Since I believe that this project should be marketed as `legacy-first` linter, we need to work on this as much as we can.

The main feature here is a "refactoring mode". What is it?

When a company has a big pile of legacy and wants to install a linter - it is absolutely impossible in the short run. But, it is achievable with a step-by-step approach. 

We already have the awesome "baseline" feature, but that is not enough.
We need two more complimentary features to help the developers with refactoring.
1. Progress report. When baseline is created we need to know how many bugs are there. We also need to know: what are the easiest to fix (by number and by impact: 10 `a,b` -> `a, b` fixes are easier than refactoring a single complexity issue). So we can recommend what to fix and track the progress over time
2. Enabling the refactoring mode. Currently we allow to push code with the same or less amount of bugs in it. We need to be able to turn "refactoring mode" on: when we are forced to reduce the amount of bugs in a file we touch at least by 1

I guess the combination of baseline, progress reports, and refactoring mode can be a boomer. 🔥

**Comment by orsinium** [comment]
You can make a simple script to get your progress from the previous baseline:

```bash
flakehell baseline > baseline-new.txt
cat baseline.txt baseline-new.txt | sort | uniq --repeated
```

However, this stat can't be used as CI rule, because in this case, you have to commit a new baseline after every merged PR. You can do it from CI, but it's considered as a bad practice.

**Comment by orsinium** [comment]
This is CI specific. For Gitlab it can be done via [code quality artifacts](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html) with [flake8-gl-codeclimate](https://github.com/awelzel/flake8-gl-codeclimate). We're planning to support it as formatter soon.
