### ISSUE TITLE
issue with pylint version 2.5.2

### ISSUE THREAD

**Issue by jnoortheen** [life4/flakehell#62]
I am starting to configure flakehell on a new project and encountered this error.

```
 ❯ flakehell codes pylint                                                                                                                            
cannot import module: cannot import name 'MSGS' from 'pylint.lint' (.virtualenvs/79hodxNg-py3.8/lib/python3.8/site-packages/pylint/lint/__init__.py)
```

**flakehell** version: 0.3.6
**pylint** version: 2.5.2

upon inspecting the api has changed since pylint version 2.5. 
could you add support to new `pylint` version  or specify the version supported in requirements ?

**Comment by orsinium** [comment]
Thank you for the report. Release in 0.4.1

**Comment by jnoortheen** [comment]
Great lightning response :)
