### ISSUE TITLE
Fix images in long_description in dist metadata

### ISSUE THREAD

**Issue by webknjaz** [life4/flakehell#63]
TL;DR PyPI doesn't host those images separately so the /dev/null placeholders look ugly.

You can fix this by either inlining the images into README or using full direct URLs to the pictures GitHub. It may also be a good idea to use SVG versions of the pics.

**Comment by orsinium** [comment]
Thank you, that's a good catch. I don't think we should tie README on Github. However, add autofixing in DepHell would be a good thing.
