### ISSUE TITLE
need glob pattern support inside exceptions rule

### ISSUE THREAD

**Issue by jnoortheen** [life4/flakehell#65]
I am glad that the per-file ignore is added to `flakehell`. 

Could you also add support for using patterns? it will be helpful in scenarios. For example inside a Django project the tests would be inside multiple folders but all having same set of rules excluded.

If regex support is added then this will become very powerful. as we can define multiple patterns using or style. 

I suggest making the current rule to be a `glob pattern/ fnmatch.fnmatch` and create new one for regex

```toml
[tool.flakehell.exceptions.re."re(.+)pattern"]
```

**Comment by orsinium** [comment]
Thank you, that's a good example. I thought about this feature but had no valid use cases in mind. Let's do it!
