### ISSUE TITLE
Plugins disabled by default, inconsistent with .flake8 config

### ISSUE THREAD

**Issue by Dreamsorcerer** [life4/flakehell#73]
The documentation claims that flakehell will work with the .flake8 config file ("Everything you’ve specified for Flake8 will work for FlakeHell."). However, it disables all the plugins by default, which makes it inconsistent (and "everything you've specified" would suggest to me that the select config should work and enable the relevant plugins).

Suggestion to enable all plugins when using a .flake8 config, and only disable them if using the pyproject.toml config.

**Comment by orsinium** [comment]
We ignore all codes-management options from flake8:
https://flakehell.readthedocs.io/config.html#ignored-options
(ah, the tables aren't supported, I'll fix it).

FlakeHell fixes old legacy problems of flake8. If it could be done with backward compatibility, it would be a part of flake8 itself. The biggest problem is the implicit selection of plugins and codes. With flakehell, the list of chack must be specified explicitly. I never want to run everything that I have installed on my machine on every project. Every project has it's own list of plugins and checks, and it must be explicitly listed.

**Comment by orsinium** [comment]
I'll clarify the docs, thank you for the report.

**Comment by Dreamsorcerer** [comment]
While that makes sense, I still feel that it should default to enable everything in order to be consistent with flake8.

If you want to selectively enable plugins, then you would be using a pyproject.toml file anyway, and this wouldn't affect you.
